name: stock-bot

on:
  schedule:
    - cron: "0 12 * * *"    # Workflow sẽ chạy 19:00 giờ Việt Nam mỗi ngày

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: install packages
        run: pip install -r requirements.txt

      - name: run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py